version: '2'

services:
  app:
    image: elim/tiarra:0.0.2
    ports:
      - 6667:6667
    restart: always
    user: $UID
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ~/.tiarra:/var/tiarra
